import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        body: "#ffffff",
        text: "#151515",
        btn: "#eeeeee",
        btn_bg: "#ffffff",
        scrollbar: "#f7f7f7",
        scrollbar_track: "#eeeeee",
        paragraph: "#777777",
        highlight: "#000000",
        inactive: "#777777",
        active: "#151515",
        card: "#f7f7f7",
        card_header: "#151515",
        work_heading: "#777778",
        card_stack: "#bebebe",
        card_description: "#949495",
        resume_card: "#f7f7f7",
        resume_title: "#151515",
        resume_divider: "#151515",
        resume_underline: "#77777859",
        form_input: "#151515",
        form_inputBg: "#f7f7f7",
        form_buttonBg: "#151515",
        form_buttonTxt: "#ffffff",
        btn_border: "#bebebe",
        success: "#198754",
        body_dark: "#151515",
        text_dark: "#ffffff",
        btn_dark: "#1b1b1d",
        btn_bg_dark: "#1b1b1d",
        scrollbar_dark: "#16161a",
        scrollbar_track_dark: "#101011",
        paragraph_dark: "#949495",
        highlight_dark: "#ffffff",
        active_dark: "#ffffff",
        inactive_dark: "#949495",
        card_dark: "#1b1b1d",
        card_header_dark: "#ffffff",
        work_heading_dark: "#777778",
        card_stack_dark: "#bebebe",
        card_description_dark: "#949495",
        resume_card_dark: "#1b1b1d",
        resume_title_dark: "#cfcfcf",
        resume_divider_dark: "#e2e2e2",
        resume_underline_dark: "#77777859",
        form_input_dark: "#d3d3d3",
        form_inputBg_dark: "#16161a",
        form_buttonBg_dark: "#16161a",
        form_buttonTxt_dark: "#ffffff",
        btn_border_dark: "#a6a6a7",
        success_dark: "#198754",
      },
    },
  },
  plugins: [],
  darkMode: "selector",
};
export default config;
